---
# tasks file for install-redis
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: InstallRedids
  apt:
    name: redis-server
    state: present

- name: InstallRedisTools
  apt:
    name: redis-tools
    state: present

- name: copy-redis-conf-file
  template:
    src: "templates/{{hosttype}}_redis.yml"
    dest:  /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: 0640
  notify: 
  - restart-redis  